### ISSUE TITLE
Incorrect Function Length

### ISSUE THREAD

**Issue by jugglinmike** [anba/es6draft#12]
[The ES6 spec defines `Symbol.prototype[Symbol.toPrimitive]` as a function with a single parameter.](http://www.ecma-international.org/ecma-262/6.0/#sec-symbol.prototype-@@toprimitive)
According to [section 17](http://www.ecma-international.org/ecma-262/6.0/#sec-ecmascript-standard-built-in-objects), in the absence of any text specifying otherwise, the function's `length` property value should be dictated by its formal parameter list:

>  Every built-in Function object, including constructors, has a length
>  property whose value is an integer. Unless otherwise specified, this value
>  is equal to the largest number of named arguments shown in the subclause
>  headings for the function description, including optional parameters.

This is a bit disappointing because the parameter isn't actually referenced in the algorithm, but I believe following the letter of the spec means defining the `length` property to `1`.

**Comment by anba** [comment]
> This is a bit disappointing because the parameter isn't actually referenced in the algorithm, but I believe following the letter of the spec means defining the length property to 1.

Yupp. I guess a copy-paste error when I initially added the function.

**Comment by jugglinmike** [comment]
Just in case there was any doubt: I meant "disappointing" to describe the confusing/unnecessary parameter, not your work here!

**Comment by anba** [comment]
No worries, I didn't misunderstand you.

**Comment by anba** [comment]
Fixed in 6eca8b8448aeca44f78798b20005951bdacc26e5

**Comment by jugglinmike** [comment]
Nice work!
