### ISSUE TITLE
Return and inner generators

### ISSUE THREAD

**Issue by mnieper** [anba/es6draft#2]
I am currently experimenting with es6draft, and I am wondering whether its behaviour with the following piece of code is correct: 

```javascript
function* f2() {
  function* g() {
    try {
      yield 1;
      yield 2;
    } finally {
      yield 3;
      print("Should be reachable???");
      yield 4;
    }
  }
  yield* g();
  yield 5;
}

var g2 = f2();
g2.next();  // -> yields {value: 1, done: false}
g2.return(42); // -> yields {value: 3, done: true}
g2.next(); // -> yields {value: undefined, done: true}
```

The comments of the form `// ->` show what es6draft returns. Is this behaviour really the one that is intended by the latest draft of ES6? For example, the print statement in the finally clause is never being executed.

(Reading the spec, it looks to me that es6draft is correct in its behaviour, but does it make sense?)

**Comment by anba** [comment]
> (Reading the spec, it looks to me that es6draft is correct in its behaviour, but does it make sense?)

There are two related issue reports on bugs.ecmascript.org:
https://bugs.ecmascript.org/show_bug.cgi?id=3526
https://bugs.ecmascript.org/show_bug.cgi?id=3395

You're on the cc-list for 3526 so you know that one already. :smile: But that report only covers `throw` completions, so it's not quite the same as your example. In 3395 it was proposed to throw a TypeError if the inner iterator returns with `done = false` for a `return` completion, however in the latest tc39 meeting the change was rejected.

IIRC an example like yours was once posted on es-discuss, and there was a discussion about whether or not inner iterators can override a request to the outer generator to close itself with a `return` completion. I guess it's time again to dig up old es-discuss threads... :sweat:

**Comment by mnieper** [comment]
I found the bug 3526 after I wrote the issue here; that's why I am on that cc-list :-)

I reported my example there because the rational seems to be the same - a wrapped generator should behave as a non-wrapped one, at least in my opinion. It may be interesting to check how Python 3.3+ handles these issues.

**Comment by anba** [comment]
Closing because I don't think there's anything actionable to do for me. For the record, this the output with the final ES2015 semantics for `yield*`:

```javascript
js> var g2 = f2();
js> g2.next()
{ value: 1, done: false }
js> g2.return(42)
{ value: 3, done: false }
js> g2.next()
Should be reachable???
{ value: 4, done: false }
js> g2.next()
{ value: 5, done: false }
js> g2.next()
{ value: (void 0), done: true }
```
