### ISSUE TITLE
Rewrite in C++

### ISSUE THREAD

**Issue by mnieper** [anba/es6draft#3]
I have to admit that I haven't taken a closer look at your code base. Do you think it is feasible to translate your work form Java to C++? In the latter case it could be compiled with Emscripten and after adapting it to the browser environment, one would have a nearly 100% complete implementation for ES6 on the browser. (And would be prepared when ES7 is specced.)

With asm.js, I don't think it would run slower than the current code in the JVM.

**Comment by anba** [comment]
Rewriting the complete project in C++ (or any other language - Rust comes to my mind) is not going to happen. That would require way too much effort, for example adding a GC, JIT compilation, etc. And I don't have the time nor the motivation to restart from scratch. :wink:

**Comment by mnieper** [comment]
Maybe there will be a stable Java compiler to LLVM one day that is able to compile your code to static LLVM bit code, which can act as input to Emscripten.

**Comment by anba** [comment]
I'm closing this feature request for the reasons outlined in my earlier comment, but thanks for raising the issue!
