### ISSUE TITLE
Interpret the dash(-) argument as /dev/stdin

### ISSUE THREAD

**Issue by ziyunfei** [anba/es6draft#5]
I'm afraid I can't explain myself very well due to my bad english, so I will give you some examples to demonstrate:
 ```shell
$ pbpaste
var foo = Number
`123`
print(typeof foo)
```
SpiderMonkey:
```shell
pbpaste | js
js> var foo = Number
js> `123`
"123"
js> print(typeof foo)
function

$ pbpaste | js -
number
```

es6draft:
```shell
$ pbpaste | ./es6draft
js> var foo = Number
js> `123`
"123"
js> print(typeof foo)
function

$ pbpaste | ./es6draft -
"-" is not a valid option

$ pbpaste | ./es6draft /dev/stdin
number
```

**Comment by anba** [comment]
> I'm afraid I can't explain myself very well due to my bad english, so I will give you some examples to demonstrate:

Ah I see, so `-` is used a shorthand in `js` to select stdin: http://hg.mozilla.org/mozilla-central/file/a27dd304348d/js/src/shell/js.cpp#l585

Should be easy to support this feature.
