### ISSUE TITLE
Promise.resolve does not honor `constructor` property

### ISSUE THREAD

**Issue by jugglinmike** [anba/es6draft#8]
If `Promise.resolve` is invoked with a Promise instance as its first argument,
that object should only be returned if its `constructor` property matches the
current "this" value.

    $ ./bin/es6draft --version
    es6draft rev38 (build: 2015-07-06T15:04:38)
    $ ./bin/es6draft
    js> var p1 = new Promise(function() {});
    js> p1.constructor = null;
    null
    js> Promise.resolve(p1) === p1
    true

(expected: false)

> [25.4.4.5](http://www.ecma-international.org/ecma-262/6.0/#sec-promise.resolve) **Promise.resolve ( x )**
>
> 1. Let C be the this value.
> 2. If Type(C) is not Object, throw a TypeError exception.
> 3. If IsPromise(x) is true,
>      1. Let xConstructor be Get(x, "constructor").
>      2. ReturnIfAbrupt(xConstructor).
>      3. If SameValue(xConstructor, C) is true, return x.

See also:

- [V8 Issue 4161: Update `Promise.resolve` to match latest TC39
  spec.](https://code.google.com/p/v8/issues/detail?id=4161)
- [tc39/test262 #358 Extend test coverage for Promise
  built-in](https://github.com/tc39/test262/pull/358)

**Comment by anba** [comment]
Thanks for letting me know! (I really need to start pushing my local updates to the repo...)

**Comment by anba** [comment]
Fixed in b90b28b12127b3c4f429be02f05a24ff66298b3e

**Comment by jugglinmike** [comment]
Great! Thanks :)
