### ISSUE TITLE
Function `name` property incorrectly derived from description-less Symbol

### ISSUE THREAD

**Issue by jugglinmike** [anba/es6draft#9]
When a function's `name` property is derived from a Symbol value that has no
description, the name should be `"[]"`.

    $ ./bin/es6draft --version
    es6draft rev38 (build: 2015-07-06T15:04:38)
    $ ./bin/es6draft -e 'var s = Symbol(); var o = { [s]: ()=>{} }; print(o[s].name);'

    $

(espected: "[]")

> [19.4.1.1](http://www.ecma-international.org/ecma-262/6.0/#sec-symbol-description) **Symbol ( [ description ] )**
>
> When Symbol is called with optional argument description, the following steps
> are taken:
>
> 1. If NewTarget is not undefined, throw a TypeError exception.
> 2. If description is undefined, let descString be undefined.
> 3. Else, let descString be ToString(description).
> 4. ReturnIfAbrupt(descString).
> 5. Return a new unique Symbol value whose [[Description]] value is descString.

---

> [9.2.11](http://www.ecma-international.org/ecma-262/6.0/#sec-setfunctionname) **SetFunctionName (F, name, prefix)**
>
> The abstract operation SetFunctionName requires a Function argument F, a
> String or Symbol argument name and optionally a String argument prefix. This
> operation adds a name property to F by performing the following steps:
>
> 1. Assert: F is an extensible object that does not have a name own property.
> 2. Assert: Type(name) is either Symbol or String.
> 3. Assert: If prefix was passed then Type(prefix) is String.
> 4. If Type(name) is Symbol, then
>    1. Let description be name’s [[Description]] value.
>    2. If description is undefined, let name be the empty String.
>    3. Else, let name be the concatenation of "[", description, and "]".
> 5. If prefix was passed, then
>    1. Let name be the concatenation of prefix, code unit 0x0020 (SPACE), and
>       name.
> 6. Return DefinePropertyOrThrow(F, "name", PropertyDescriptor{[[Value]]:
>    name, [[Writable]]: false, [[Enumerable]]: false, [[Configurable]]:
>    true}).
> 7. Assert: the result is never an abrupt completion.

**Comment by anba** [comment]
But SetFunctionName, step 4.ii sets the `name` variable to the empty string if the symbol's description is `undefined`.

**Comment by jugglinmike** [comment]
That "Else" is step 4.iii is important, isn't it? Sorry for the noise.

**Comment by anba** [comment]
No problem. :smiley:
